title: Baila la Vida
author: Chocobango
email: chocobango@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Porque bailar la vida es la solucion a tus problemas
    

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
